# hosts.yml - Ansible inventory configuration
# This inventory file defines two different ways to connect to the same F5OS device

all:
  children:
    # F5OS group - For REST API interactions via HTTPS
    # This method is used for F5OS platform configuration and monitoring
    f5os:
      hosts:
        # Logical hostname for F5OS API access
        r5900-2-f5os:
          # Physical hostname/IP of the device
          # Only basic connectivity needed here as F5OS REST API details are in playbook
          ansible_host: r5900-2

    # Linux group - For direct Linux shell access via SSH
    # This method is used to access the underlying Linux OS
    linux_hosts:
      hosts:
        # Logical hostname for Linux SSH access
        r5900-2-linux:
          # Same physical device as above, different connection method
          ansible_host: r5900-2
          # Linux root credentials - password will be prompted using --ask-pass
          ansible_user: root
          # Specify SSH as connection type (vs httpapi for F5OS)
          ansible_connection: ssh
          # Don't escalate privileges (already root)
          ansible_become: no
          # Specify Python interpreter on the F5OS device
          ansible_python_interpreter: /usr/bin/python3
          # SSH specific settings to bypass host key checking
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
